refresh_rate: 30 seconds
appenders:
  stdout:
    kind: console
    encoder:
      pattern: "{d(%+)(utc)} [{f}:{L}] {h({l})} {M}:{m}{n}"
  server:
    kind: file
    path: "logs/server.log"
    encoder:
      pattern: "{d(%+)(utc)} [{f}:{L}] {h({l})} {M}:{m}{n}"
root:
  level: debug
  appenders:
    - stdout
    - server
# loggers:
#   app::backend::db:
#     level: info
#   app::requests:
#     level: info
#     appenders:
#       - requests
#     additive: false